### ISSUE TITLE
Make UserActivation a NoInterfaceObject?

### ISSUE THREAD

**Issue by RByers** [dtapuska/useractivation#3]
No point in adding window.UserActivation (in addition to window.userActivation) is there?

**Comment by dtapuska** [comment]
I wasn't sure about this. What is the predictability of changing UserActivation to be an EventTarget in the future if we want events dispatched to it? I presume it is fine; that we set it as NoInterfaceObject and then later allow it to have an Interface?

**Comment by RByers** [comment]
Still shouldn't need an interface object.  I.e. clients will use `window.userActivation.addEventListener(...)` right?  I think we only need the interface object for `new`.

**Comment by domenic** [comment]
This should be reversed, ideally. NoInterfaceObject is legacy, and we are trying to restrict its spread. See the note in the Web IDL psec.

**Comment by RByers** [comment]
Ah, thanks @domenic!  I mentioned to Dave there might be a guideline like that.  Sorry I lead you astray here Dave!
